<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE branches
[
<!ELEMENT branches (branch*)>
<!ELEMENT branch (address, contact, hours, mapsLink)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT hours (#PCDATA)>
<!ELEMENT mapsLink (#PCDATA)>
]>

<branches>
    <branch>
        <address>
            76 Devonshire St, Surry Hills NSW
        </address>
        <contact>
            02 9211 1234
        </contact>
        <hours>
            Mon - Fri: 6:00 to 14:30, Sat-Sun: 7:00 to 15:00
        </hours>
        <mapsLink>  https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3312.1439926220064!2d151.2055571510855!3d-33.885945227285795!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b12ae21aea44cd5%3A0xcf2d54666d7cca73!2s76%20Devonshire%20St%2C%20Surry%20Hills%20NSW%202010!5e0!3m2!1sen!2sau!4v1635563084250!5m2!1sen!2sau
        </mapsLink>
    </branch>
    <branch>
        <address>
            451 Pitt St, Haymarket Sydney, NSW
        </address>
        <contact>
            02 9262 5678
        </contact>
        <hours>
            Mon - Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00
        </hours>
        <mapsLink>  https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3312.3895345548463!2d151.2045780510852!3d-33.87962032695761!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b12ae23192f282b%3A0x506728c0b18a4f49!2s451%20Pitt%20St%2C%20Sydney%20NSW%202000!5e0!3m2!1sen!2sau!4v1635563230151!5m2!1sen!2sau
        </mapsLink>
    </branch>
    <branch>
        <address>
            31 Alfred Street, Circular Quay, NSW
        </address>
        <contact>
            02 8971 9101
        </contact>
        <hours>
            Mon - Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00        
        </hours>
        <mapsLink> https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3313.0661934495433!2d151.20871185108481!3d-33.86218492605258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b12ae69daa2f96f%3A0x735f85193da40a66!2s31%20Alfred%20St%2C%20Sydney%20NSW%202000!5e0!3m2!1sen!2sau!4v1635563268476!5m2!1sen!2sau
        </mapsLink>
    </branch>
</branches>
